### ISSUE TITLE
Please add timestamp_ms to the bidtrace api

### ISSUE THREAD

**Issue by krasi-georgiev** [eden-network/mev-boost-relay#25]
the as what flashbot exposes in
https://boost-relay.flashbots.net/relay/v1/data/bidtraces/builder_blocks_received?block_number=16046700
"timestamp_ms"

**Comment by chpiatt** [comment]
We now provide timestamp_ms, see: https://relay.edennetwork.io/relay/v1/data/bidtraces/builder_blocks_received?block_number=16598953
